#!/bin/sh
# tat-nguy-4 : VTEP leaf for VXLAN 10 (BADASS P3)

# ---- Linux side: bridge + VXLAN tunnel ----
ip link add br0 type bridge
ip link set br0 up

ip link add vxlan10 type vxlan id 10 dstport 4789 local 1.1.1.4 nolearning
ip link set vxlan10 master br0
ip link set vxlan10 up

ip link set eth0 master br0
ip link set eth0 up
