!
! Zebra configuration file
!
frr version 10.0
frr defaults traditional
!
hostname tat-nguy-router
!
log stdout
!
!
router bgp 65001
 bgp router-id 10.0.0.1
!
router ospf
 ospf router-id 10.0.0.1
!
router isis CORE
 net 49.0001.0000.0000.0001.00
 is-type level-2-only
!
line vty
!